# Generated by Django 5.1.7 on 2025-04-09 09:21

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client's full name or company name", max_length=20, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Additional information about the client', null=True, verbose_name='Description')),
                ('client_id', models.CharField(default=core.utils.generate_client_key, editable=False, help_text='Client ID', max_length=40, unique=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(default=core.utils.generate_client_key, editable=False, help_text='Client secret', max_length=40, unique=True, verbose_name='Client secret')),
                ('product_name', models.CharField(help_text='Description of a product which provided by client', max_length=80, verbose_name='Product name')),
                ('sku_prefix', models.CharField(blank=True, help_text='SKU prefix for the product (if not set, will be automatically generated)', max_length=4, verbose_name='SKU prefix')),
                ('image_url', models.URLField(blank=True, help_text='The image URL for the product', null=True, verbose_name='image url')),
                ('home_url', models.URLField(blank=True, help_text='The home page URL for the product', null=True, verbose_name='home url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_enabled', models.BooleanField(default=False, help_text='Designates whether this client is active', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSOUser',
            fields=[
                ('sub', models.UUIDField(editable=False, help_text='Unique identifier from SSO provider', primary_key=True, serialize=False, unique=True, verbose_name='Subject Identifier')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'SSO User',
                'verbose_name_plural': 'SSO Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
