# Generated by Django 5.1.7 on 2025-04-14 16:01

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='home_url',
        ),
        migrations.RemoveField(
            model_name='client',
            name='image_url',
        ),
        migrations.AddField(
            model_name='client',
            name='cancel_url',
            field=models.URLField(blank=True, help_text='the URL of the product page where users are redirected if they cancel the payment. If not provided, the Return URL will be used.', null=True, verbose_name='Cancel URL'),
        ),
        migrations.AddField(
            model_name='client',
            name='return_url',
            field=models.URLField(blank=True, help_text='the URL of the product page where users are redirected after completing a payment.', null=True, verbose_name='кeturn URL'),
        ),
        migrations.AlterField(
            model_name='client',
            name='product_name',
            field=models.CharField(help_text='description of a product which provided by client', max_length=80, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sku_prefix',
            field=models.CharField(blank=True, default=core.utils.generate_sku_prefix, help_text='SKU prefix for the product (will be automatically generated if skipped)', max_length=4, verbose_name='SKU prefix'),
        ),
        migrations.AlterField(
            model_name='ssoidentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_identities', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='user'),
        ),
    ]
