# Generated by Django 5.1.7 on 2025-04-08 14:14

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(default=core.utils.generate_client_key, editable=False, help_text='Client ID', max_length=40, unique=True, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_secret',
            field=models.CharField(default=core.utils.generate_client_key, editable=False, help_text='Client secret', max_length=40, unique=True, verbose_name='Client secret'),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
