# Generated by Django 5.1.7 on 2025-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cancel_url',
        ),
        migrations.RemoveField(
            model_name='client',
            name='return_url',
        ),
        migrations.AddField(
            model_name='client',
            name='allowed_redirect_domains',
            field=models.TextField(blank=True, help_text='A newline-separated list of domains that are allowed for redirect URLs.', null=True, verbose_name='allowed redirect domains'),
        ),
    ]
