# Generated by Django 5.1.7 on 2025-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mailing_subscribed',
            field=models.BooleanField(default=True, verbose_name='is mailing subscribed'),
        ),
    ]
