# Generated by Django 5.1.7 on 2025-04-12 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOIdentity',
            fields=[
                ('sub', models.UUIDField(help_text='unique identifier from sso provider', primary_key=True, serialize=False, unique=True, verbose_name='subject identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'sso identity',
                'verbose_name_plural': 'sso identities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UserIdentity',
        ),
    ]
