services:
  pdj_server:
    image: dev1dor/pdj:1.0.3
    restart: always
    container_name: pdj_server
    command: gunicorn --access-logfile - --error-logfile - -b 0.0.0.0:8000 --workers 4 core.wsgi
    env_file:
      - .env
    volumes:
      - static_volume:/var/www/pdj/static
      - media_volume:/var/www/pdj/media
    networks:
      - pg_network
      - redis_network
      - nginx_network
    depends_on:
      - postgres
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
  pdj_worker:
    image: dev1dor/pdj:1.0.3
    restart: always
    container_name: pdj_worker
    env_file:
      - .env
    networks:
      - pg_network
      - redis_network
    command: >
      celery -A core worker -l info -c 2 -E
    depends_on:
      - postgres
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
  pdj_beat:
    image: dev1dor/pdj:1.0.3
    container_name: pdj_beat
    restart: always
    env_file:
      - .env
    networks:
      - pg_network
      - redis_network
    command: >
      sh -c "celery -A core beat -l info --pidfile=/tmp/celeryd.pid"
    depends_on:
      - postgres
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
  postgres:
    image: postgres:17.4
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-pdj}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    networks:
      - pg_network
    volumes:
      - pg_volume:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
  redis:
    image: redis:7.4.2-bookworm
    restart: always
    networks:
      - redis_network
    volumes:
      - redis_volume:/data
    logging:
      driver: "json-file"
      options:
        max-size: "512m"

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: always
    env_file:
      - ./configs/nginx/prod/nginx-certbot.env
    environment:
      - PDJ_DOMAIN=pdj.mydomain.com
      - CORS_ALLOWED_ORIGINS=*
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - static_volume:/var/www/pdj/static
      - media_volume:/var/www/pdj/media
      - ./configs/nginx/prod/templates:/etc/nginx/templates
    networks:
      - nginx_network
    depends_on:
      - pdj_server
    logging:
      driver: "json-file"
      options:
        max-size: "512m"

networks:
  pg_network:
    driver: bridge
  redis_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  pg_volume:
  redis_volume:
  static_volume:
  media_volume:
  nginx_secrets:
