# Generated by Django 5.1.7 on 2025-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['type'], 'verbose_name': 'email template', 'verbose_name_plural': 'email templates'},
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('base', 'base'), ('payment_success', 'payment_success'), ('subscription_canceled', 'subscription_canceled'), ('subscription_renewal', 'subscription_renewal')], max_length=64, verbose_name='type'),
        ),
    ]
