# Generated by Django 5.1.7 on 2025-04-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['created_at'], 'verbose_name': 'email template', 'verbose_name_plural': 'email templates'},
        ),
    ]
