# Generated by Django 5.1.7 on 2025-04-15 11:52

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0002_alter_emailtemplate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
    ]
