# Generated by Django 5.1.7 on 2025-04-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_type', models.CharField(choices=[('paypal', 'PayPal')], help_text='The payment processor type', max_length=20, unique=True, verbose_name='Processor Type')),
                ('client_id', models.CharField(blank=True, help_text='Client ID', max_length=255, null=True, verbose_name='Client ID')),
                ('secret', models.CharField(help_text='Secret', max_length=255, verbose_name='Secret')),
                ('endpoint_secret', models.CharField(blank=True, help_text='Secret used to verify webhook payloads (optional)', max_length=255, null=True, verbose_name='Webhook Secret')),
                ('is_sandbox', models.BooleanField(default=True, help_text='Indicates if these credentials relates to sandbox', verbose_name='Is Sandbox')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if these credentials are currently active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Processor',
                'verbose_name_plural': 'Processors',
                'ordering': ['processor_type'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the related object', verbose_name='Object ID')),
                ('external_id', models.CharField(help_text='Unique identifier from the payment provider', max_length=128, verbose_name='External ID')),
                ('content_type', models.ForeignKey(help_text='The type of object this payment relates to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('processor', models.ForeignKey(help_text='The payment processor service', on_delete=django.db.models.deletion.CASCADE, to='provider.processor', verbose_name='Processor')),
            ],
            options={
                'verbose_name': 'Payment Reference',
                'verbose_name_plural': 'Payment References',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='provider_pa_content_e29a62_idx')],
                'unique_together': {('processor', 'external_id')},
            },
        ),
    ]
