# Generated by Django 5.1.7 on 2025-04-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indicates if these credentials are currently active', verbose_name='Is Active'),
        ),
    ]
