# Generated by Django 5.1.7 on 2025-04-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_alter_processor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='processor_type',
            field=models.CharField(choices=[('paypal', 'PayPal')], help_text='The payment processor type', max_length=20, verbose_name='Processor Type'),
        ),
        migrations.AlterUniqueTogether(
            name='processor',
            unique_together={('processor_type', 'secret')},
        ),
    ]
