# Generated by Django 5.1.7 on 2025-04-09 09:21

import core.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the plan', max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of a plan', null=True, verbose_name='Description')),
                ('period', models.PositiveIntegerField(choices=[(1, 'Day'), (2, 'Week'), (3, 'Month'), (4, 'Year')], help_text='Billing period duration type', verbose_name='Period')),
                ('term', models.IntegerField(default=1, help_text='Number of periods (e.g., 1 month, 2 years)', verbose_name='Term')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the plan in the specified currency', max_digits=40, verbose_name='Price')),
                ('is_recurring', models.BooleanField(default=True, help_text='Whether the plan automatically renews', verbose_name='Is Recurring')),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether the plan is available for use', verbose_name='Is Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the plan was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('client', models.ForeignKey(help_text='The client for plan', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_type', models.CharField(choices=[('paypal', 'PayPal')], help_text='The payment processor type', max_length=20, verbose_name='Processor Type')),
                ('client_id', models.CharField(blank=True, help_text='Client ID', max_length=255, null=True, verbose_name='Client ID')),
                ('secret', models.CharField(help_text='Secret', max_length=255, verbose_name='Secret')),
                ('endpoint_secret', models.CharField(blank=True, help_text='Secret used to verify webhook payloads for provider (optional)', max_length=255, null=True, verbose_name='Endpoint Secret')),
                ('webhook_secret', models.CharField(default=core.utils.generate_enpoint_secret, editable=False, help_text='Secret used to create link for webhook route', max_length=40, unique=True, verbose_name='Webhook Secret')),
                ('is_sandbox', models.BooleanField(default=True, help_text='Indicates if these credentials relates to sandbox', verbose_name='Is Sandbox')),
                ('is_enabled', models.BooleanField(default=False, help_text='Indicates if these credentials are currently active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Processor',
                'verbose_name_plural': 'Processors',
                'ordering': ['processor_type'],
                'unique_together': {('processor_type', 'secret')},
            },
        ),
        migrations.CreateModel(
            name='PlanProcessorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128, unique=True, verbose_name='external_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='payments.plan', verbose_name='plan')),
                ('processor', models.ForeignKey(help_text='The payment processor service', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='payments.processor', verbose_name='Processor')),
            ],
            options={
                'verbose_name': 'Plan processor link',
                'verbose_name_plural': 'Plan processor links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(help_text='Unique identifier for tracking subscriptions with payment processors', max_length=127, verbose_name='Tracking ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Hold'), (3, 'Canceled'), (4, 'Failure'), (5, 'Success'), (6, 'Expired')], default=1, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.ssouser', verbose_name='user')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.plan', verbose_name='plan')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.processor', verbose_name='processor')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'unique_together': {('id', 'tracking_id')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128, unique=True, verbose_name='external_id')),
                ('start_at', models.DateTimeField(editable=False, verbose_name='start at')),
                ('end_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='end at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='payments.payment', verbose_name='payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.ssouser', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
