# Generated by Django 5.1.7 on 2025-04-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='external_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='external_id',
            field=models.CharField(default='1', max_length=128, unique=True, verbose_name='external_id'),
            preserve_default=False,
        ),
    ]
