# Generated by Django 5.1.7 on 2025-04-04 16:54

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='endpoint_secret',
            field=models.CharField(blank=True, default=core.utils.generate_enpoint_secret, editable=False, help_text='Secret used to verify webhook payloads', max_length=40, unique=True, verbose_name='Webhook Secret'),
        ),
    ]
