# Generated by Django 5.1.7 on 2025-04-25 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user_id', '-created_at'], name='idx_sub_user_id_created_at'),
        ),
    ]
