# Generated by Django 5.1.7 on 2025-04-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='suspend_at',
        ),
        migrations.AddField(
            model_name='subscription',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='suspended at'),
        ),
    ]
