# Generated by Django 5.1.7 on 2025-04-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_subscription_external_id_payment_external_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('id', 'external_id')},
        ),
        migrations.AlterField(
            model_name='payment',
            name='external_id',
            field=models.CharField(max_length=128, verbose_name='external_id'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tracking_id',
        ),
    ]
