# Generated by Django 5.1.7 on 2025-04-14 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_plan_code_alter_plan_client_alter_plan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(blank=True, help_text='Unique, machine-readable name for the plan (e.g., for syncing with external systems)', max_length=128, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Code must contain only lowercase letters, numbers, or hyphens', regex='^[a-z0-9-]+$')], verbose_name='code'),
        ),
    ]
