# Generated by Django 5.1.7 on 2025-04-04 17:04

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_processor_endpoint_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='webhook_secret',
            field=models.CharField(default=core.utils.generate_enpoint_secret, editable=False, help_text='Secret used to create link for webhook route', max_length=40, unique=True, verbose_name='Webhook Secret'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='endpoint_secret',
            field=models.CharField(blank=True, help_text='Secret used to verify webhook payloads for provider (optional)', max_length=255, null=True, verbose_name='Endpoint Secret'),
        ),
    ]
