# Generated by Django 5.1.7 on 2025-06-16 11:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription_idx_sub_user_id_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Unique identifier for the feature, used in code', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Key must contain only lowercase letters, numbers, or underscores (snake_case)', regex='^[a-z0-9_]+$')], verbose_name='key')),
                ('name', models.CharField(help_text='Name of the feature', max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Description of a feature', null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(help_text='Optional value for the feature (e.g., limit, quota)', max_length=256, verbose_name='value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='payments.feature', verbose_name='feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='payments.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'plan feature',
                'verbose_name_plural': 'plan features',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='plans',
            field=models.ManyToManyField(help_text='Plans that include this feature', related_name='features', through='payments.PlanFeature', to='payments.plan', verbose_name='plans'),
        ),
        migrations.AddConstraint(
            model_name='planfeature',
            constraint=models.UniqueConstraint(fields=('plan', 'feature'), name='unique_plan_feature', violation_error_message='This feature is already linked to the plan.'),
        ),
    ]
