# Generated by Django 5.1.7 on 2025-04-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_subscription_suspend_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planprocessorlink',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='external_id'),
        ),
    ]
