# Generated by Django 5.1.7 on 2025-04-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_processor_webhook_secret_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='tier',
            new_name='plan',
        ),
    ]
