# Generated by Django 5.1.7 on 2025-04-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_planprocessorlink_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='external_id',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='external_id'),
        ),
    ]
