# Generated by Django 5.1.7 on 2025-06-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_feature_planfeature_feature_plans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Position of the plan in the API list (lower is higher priority)', verbose_name='position'),
        ),
    ]
