# Generated by Django 5.1.7 on 2025-06-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_plan_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this plan is the default for the client', verbose_name='is default'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='position',
            field=models.PositiveIntegerField(blank=True, help_text='Position of the plan in the API list (lower is higher priority)', null=True, verbose_name='position'),
        ),
    ]
