# Generated by Django 5.1.7 on 2025-06-18 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_plan_is_default_alter_plan_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Canceled'), (3, 'Success'), (4, 'Failure'), (5, 'Expired'), (6, 'Refunded')], default=1, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='Type of the webhook event (e.g., payment.completed)', max_length=128, verbose_name='event type')),
                ('event_id', models.CharField(max_length=128, verbose_name='event id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of the event', verbose_name='created at')),
                ('payload', models.JSONField(help_text='The JSON payload of the webhook event', verbose_name='payload')),
                ('is_processed', models.BooleanField(default=False, help_text='Indicates if the webhook event has been processed', verbose_name='is processed')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='payments.processor', verbose_name='processor')),
            ],
            options={
                'verbose_name': 'webhook event',
                'verbose_name_plural': 'webhook events',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('processor', 'event_type', 'event_id'), name='unique_webhook_event', violation_error_message='This event has already been processed.')],
            },
        ),
    ]
