# Generated by Django 5.1.7 on 2025-06-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_invoice_status_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='processors',
            field=models.ManyToManyField(help_text='Payment processors linked to this plan', related_name='plans', through='payments.PlanProcessorLink', to='payments.processor', verbose_name='processors'),
        ),
        migrations.AddField(
            model_name='planprocessorlink',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the link was last synced with the processor', null=True, verbose_name='synced at'),
        ),
        migrations.AddField(
            model_name='planprocessorlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddConstraint(
            model_name='planprocessorlink',
            constraint=models.UniqueConstraint(fields=('plan', 'processor'), name='unique_plan_processor_link', violation_error_message='This processor is already linked to the plan.'),
        ),
    ]
