# Generated by Django 5.1.7 on 2025-06-24 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_plan_processors_planprocessorlink_synced_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentUrlCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('subscribe', 'Subscribe'), ('changeplan', 'Change Plan')], help_text='Type of the cached URL', max_length=64, verbose_name='type')),
                ('key', models.CharField(help_text='Unique key for the cached URL, used to identify the cache entry', max_length=255, verbose_name='key')),
                ('url', models.URLField(help_text='The cached URL for the payment processor', verbose_name='URL')),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processor', models.ForeignKey(blank=True, help_text='The payment processor for which the URL is cached', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_url_cache', to='payments.processor', verbose_name='processor')),
            ],
            options={
                'verbose_name': 'payment URL cache',
                'verbose_name_plural': 'payment URL caches',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('type', 'key'), name='unique_payment_url_cache', violation_error_message='This URL cache already exists.')],
            },
        ),
    ]
