# Generated by Django 5.1.7 on 2025-04-03 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the plan', max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of a plan', null=True, verbose_name='Description')),
                ('period', models.PositiveIntegerField(choices=[(1, 'Day'), (2, 'Week'), (3, 'Month'), (4, 'Year')], help_text='Billing period duration type', verbose_name='Period')),
                ('term', models.IntegerField(default=1, help_text='Number of periods (e.g., 1 month, 2 years)', verbose_name='Term')),
                ('is_recurring', models.BooleanField(default=True, help_text='Whether the plan automatically renews', verbose_name='Is Recurring')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the plan in the specified currency', max_digits=40, verbose_name='Price')),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether the plan is available for use', verbose_name='Is Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the plan was created', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Hold'), (3, 'Canceled'), (4, 'Failure'), (5, 'Success'), (6, 'Expired')], default=1, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extra_data', models.JSONField(null=True, verbose_name='extra data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.ssouser', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(editable=False, verbose_name='start at')),
                ('end_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='end at')),
                ('next_billing_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='next billing at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payment.order', verbose_name='order')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payment.plan', verbose_name='plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.ssouser', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
