# Generated by Django 5.1.7 on 2025-04-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_token_key'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='client',
            field=models.ForeignKey(help_text='The client for plan', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.client', verbose_name='Client'),
            preserve_default=False,
        ),
    ]
