# Generated by Django 5.1.7 on 2025-04-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_plan_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
