# Generated by Django 5.1.7 on 2025-04-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client's full name or company name", max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Additional information about the client', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this client is active', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSOUser',
            fields=[
                ('sub', models.UUIDField(editable=False, help_text='Unique identifier from SSO provider', primary_key=True, serialize=False, unique=True, verbose_name='Subject Identifier')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'SSO User',
                'verbose_name_plural': 'SSO Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this token is active', verbose_name='Is Active')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='core.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
