# Generated by Django 5.1.7 on 2025-04-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(blank=True, help_text='Token key (leave empty to autogenerate)', max_length=40, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
