# Generated by Django 5.1.7 on 2025-04-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this client is active', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='token',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this token is active', verbose_name='Is Active'),
        ),
    ]
